spring:
  application:
    name: db-migrator
  config:
    activate:
      on-profile: default
  batch:
    job:
      enabled: false
      names: userMigrationJob
    jdbc:
      initialize-schema: always
  datasource:
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/newdb